defaults:
  - _self_  # relative position of_this_ config file in the defaults list
  - rl_config: defaults
    # overwrites `rl_params`
    batch_size: 512
  - env_config: defaults
    agent_observation_mode: SEER
experiment_name: one_rainbow_against_4_oracle_1_random_agent
agents:
  - rainbow_learner
  - oracle
  - oracle
  - oracle
  - oracle
  - random_agent

num_parallel_envs: 1
logdir_subdirs:
  - .
  - v4
  - vs_oracle
  -
