defaults:
  - env_config: default
  - rl_config: default
  - _self_  # relative position of_this_ config file in the defaults list
# overwrites
rl_config:
  batch_size: 512
env_config:
  agent_observation_mode: AgentObservationType.SEER
# CONFIG VALUES
experiment_name: one_rainbow_against_4_oracle_1_random_agent
agents:
  - rainbow_learner
  - oracle
  - oracle
  - oracle
  - oracle
  - random_agent
num_parallel_envs: 1
logdir_subdirs:
  - .
  - v5
  - "${experiment_name}"
